-- 日期时间相关函数
-- CURRENT_DATE()  当前日期
SELECT CURRENT_DATE() FROM DUAL;
-- CURRENT_TIME() 当前时间
SELECT CURRENT_TIME() FROM DUAL;
-- CURRENT_TIMESTAMP() 当前时间戳
SELECT CURRENT_TIMESTAMP() FROM DUAL;

-- 创建测试表 信息表
CREATE TABLE mes (id INT,content VARCHAR(30),send_time DATETIME);

-- 添加一条记录
INSERT INTO mes 
	VALUES(1,'北京新闻',CURRENT_TIMESTAMP());	
SELECT * FROM MES;


